# Generated by Django 5.1.6 on 2025-02-17 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateDue', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_payments', models.IntegerField(default=1)),
                ('transaction_id', models.TextField()),
                ('payment_pic', models.ImageField(upload_to='')),
                ('verified', models.BooleanField()),
                ('payment_datetime', models.DateTimeField()),
                ('Payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
